[![Build Status](https://app.travis-ci.com/ErikSSWE/jsramverk-FE.svg?branch=main)](https://app.travis-ci.com/ErikSSWE/jsramverk-FE)

language: node_js

node_js:
    - "node"

addons:
  chrome: stable

sudo: false

before_script:
    - npm install

script:
    - npm run test:e2e
